In [4]:
import pandas as pd
import factor_analyzer as fa
import numpy as np
from factor_analyzer import (ConfirmatoryFactorAnalyzer,ModelSpecificationParser)

In [7]:
file = './factor_analyzer-master/tests/data/test11.csv'
X = pd.read_csv(file)
X.head(5)

V1        V2        V3        V4        V5        V6        V7  \
0 -1.072079 -0.043300 -0.709732  0.882942 -0.188851 -0.869359 -1.952088   
1  3.604727  0.218592 -0.368387  1.588172  0.899240  1.072192 -0.094796   
2 -1.043321  0.015767 -0.665354  0.758331  1.822933  2.294757  2.735671   
3 -0.073700 -0.593059 -0.124759  0.206948  0.882141 -1.905872 -1.537082   
4 -0.099293  0.477685 -1.113991 -0.285073 -0.646117  0.772950  0.847903   

         V8  
0 -0.825175  
1  1.351627  
2  0.987119  
3 -0.962797  
4 -0.613892

In [8]:
model_dict = {"F1": ["V1", "V2", "V3", "V4"],"F2": ["V5", "V6", "V7", "V8"]}  # 定义验证性因子分析模型
model_spec = ModelSpecificationParser.parse_model_specification_from_dict(X, model_dict)  # 将上述的字典类型转化为ModelSpecificaition object
cfa = ConfirmatoryFactorAnalyzer(model_spec, disp=False)  # 定义cfa
cfa.fit(X.values)  # 训练模型

ConfirmatoryFactorAnalyzer(bounds=None, disp=False, impute='median',
              is_cov_matrix=False, max_iter=200, n_obs=1000,
              specification=<factor_analyzer.confirmatory_factor_analyzer.ModelSpecification object at 0x000000C8A885C518>,
              tol=None)

In [9]:
# 因子载荷，列是factor1和factor2，行是V1-V8
cfa.loadings_

array([[0.        , 0.99130908],
       [0.        , 0.46074998],
       [0.        , 0.35022636],
       [0.        , 0.58331317],
       [0.98621196, 0.        ],
       [0.73389127, 0.        ],
       [0.37602844, 0.        ],
       [0.50049351, 0.        ]])

In [10]:
# The factor covariance matrix.因子的协方差矩阵
cfa.factor_varcovs_

array([[1.        , 0.17385554],
       [0.17385554, 1.        ]])

In [14]:
cfa.error_vars_

array([[1.09668632],
       [0.95474338],
       [0.95099009],
       [0.9478349 ],
       [1.06382412],
       [0.9422038 ],
       [0.97622041],
       [1.038387  ]])

In [11]:
# Get the standard errors from the implied covariance matrix and implied means.
# returns
# loadings_se (numpy array) – The standard errors for the factor loadings.
# error_vars_se (numpy array) – The standard errors for the error variances.

cfa.get_standard_errors()

(array([[0.        , 0.06779945],
        [0.        , 0.04369964],
        [0.        , 0.04153118],
        [0.        , 0.04766643],
        [0.06025353, 0.        ],
        [0.04913152, 0.        ],
        [0.04066038, 0.        ],
        [0.04351207, 0.        ]]),
 array([0.11929833, 0.05043623, 0.04645805, 0.05803075, 0.10176925,
        0.06607525, 0.04742316, 0.05373641]))

In [12]:
# Get the factor scores for new data set.
cfa.transform(X.values)

array([[-1.08707717, -0.46852109],
       [ 1.20227702,  2.59025679],
       [ 2.65696993, -0.47215925],
       ...,
       [-0.91804633, -1.59309265],
       [ 0.88174826,  0.19431187],
       [-0.76951043, -0.27863464]])